package bsep.integration.predefined;
import tim6.bsep.SIEMCenter.model.drools.LogWrapper;
import tim6.bsep.SIEMCenter.model.drools.Alarm
import tim6.bsep.SIEMCenter.model.enums.SeverityLevel

rule "Emergency"
    when
        $logWrapper: LogWrapper(log.getSeverityLevel() == SeverityLevel.EMERGENCY, handled == false)
    then
        System.out.println("Emergency");
        Alarm alarm = new Alarm($logWrapper.getLog(), SeverityLevel.EMERGENCY, $logWrapper.getLog().getMessage());
        $logWrapper.setHandled(true);
        update($logWrapper);
        insert(alarm);
end
